# Site settings
title: peekbank
email: mcfrank@stanford.edu
description: >
  The peekbank Project -- Documentation and Tutorials
lang: en-US

baseurl: "/peekbank-website" # the subpath of your site, here we use "" because we are using a virtual proxy via stanford to redirect to this site
url: https://peekbank.github.io/ # the base hostname & protocol for your site
git_address: http://github.com/peekbank/peekbank-website
git_edit_address: http://github.com/peekbank/peekbank-website/blob/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: yeti

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:

- scope:
    path: _docs
    type: docs
  values:
    layout: docs_no_navbar
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
